## Домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Python_Introduction_2022</b>» в github 

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
print(np.arange(-1.3,2.5,(2.5+1.3)/64))


[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [5]:
x=[1,2,3]
n=np.random.randint(1,100)
print(np.array(n*x))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1
 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2
 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3
 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1
 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2
 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [11]:
n=np.zeros(10)
for i in range(10):
    n[i]=2*i+1
print(n)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [15]:
n=np.zeros([10,10])
n[0]=n[9]=1
n=np.transpose(n)
n[0]=n[9]=1
#
print(n)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [24]:
n=np.zeros([8,8])
for i in range (8):
    for j in range (8):
        if (i+j)%2==1:
            n[i,j]=1
print(n)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [32]:
def matrix(n):
    x=np.zeros([n,n])
    for i in range(n):
        for j in range(n):
            x[i,j]=i+j
    return(x)
print(matrix(3))

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [31]:
import numpy as np
np.dot(2,2)

np.dot(2,np.array([5,4,3,2,1]))

A=np.arange(10)
B=np.arange(4,14)
C=np.random.randint(10, size=(10,10))
D=np.random.randint(10, size=(10,10))

np.dot(A,B) 

np.dot(A,C)

np.dot(C,D) 

array([[ 80, 117, 124,  57, 135, 134,  92,  82,  88,  71],
       [139, 166, 190, 101, 201, 153, 185, 158, 187, 126],
       [135, 143, 286, 147, 170, 174, 187, 182, 210, 111],
       [126, 189, 201, 125, 191, 230, 166, 170, 188,  84],
       [222, 223, 301, 140, 251, 185, 275, 198, 283, 218],
       [150, 214, 207, 138, 193, 213, 254, 214, 232,  97],
       [155, 172, 215, 153, 199, 180, 234, 165, 223, 160],
       [130, 194, 181, 138, 131, 170, 257, 171, 194,  96],
       [154, 157, 243, 182, 255, 177, 291, 211, 246, 161],
       [117, 238, 218, 220, 244, 261, 294, 209, 190, 117]])

8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [ ]:
sin_8 = [np.sin(i) for i in np.arange(0, 1.05, 0.05)]
print(sin_8)

cos_8 = [np.cos(i) for i in np.arange(0, 1.05, 0.05)]
print(cos_8)

sin_8 = str(sin_8) + str(cos_8)
print(sin_8)

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [38]:
A = np.random.rand(3,5)
A=A*4-1
A

array([[ 1.67302182,  2.68066197,  0.81831035,  0.54855011, -0.88256362],
       [-0.33928323,  0.81968899,  2.82479908,  2.09069365,  0.1055746 ],
       [ 0.50314443,  1.79555596,  1.70738393, -0.21859155,  1.97141847]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [44]:
print(A.sum(axis=0)) #сумма по столбцам
print(A.sum(axis=1)) #сумма по строкам
print(A.sum()) #сумма всех элементов
print(A.mean(axis=1)) #построчное среднее значение
print(A.var(axis=1)) # построчная дисперсия
print(A.std(axis=1)) #построчное стандартное отклонение

[1.83688301 5.29590692 5.35049336 2.42065221 1.19442946]
[4.83798063 5.50147309 5.75891124]
16.09836496401389
[0.96759613 1.10029462 1.15178225]
[1.41063938 1.41907954 0.73871934]
[1.1877034  1.19125125 0.85948784]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [45]:
for i in range (3):
    for j in range (5):
        A[i,j] = (A[i,j] - np.mean(A[i]))/np.std(A[i])
print(A)

[[ 0.59394095  1.69666808  0.31743066  0.11405537 -1.5059646 ]
 [-1.20845863 -0.07474605  1.39835266  1.40307587 -0.22200531]
 [-0.75467946  0.77982177  0.95486449 -0.8038702   1.444163  ]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [50]:
print(A)

A[:, 2]=A[:, 2][np.argsort(A[:, 2])]
print("New", A)

[[ 0.59394095  1.69666808  0.31743066  0.11405537 -1.5059646 ]
 [-1.20845863 -0.07474605  0.95486449  1.40307587 -0.22200531]
 [-0.75467946  0.77982177  1.39835266 -0.8038702   1.444163  ]]
New [[ 0.59394095  1.69666808  0.31743066  0.11405537 -1.5059646 ]
 [-1.20845863 -0.07474605  0.95486449  1.40307587 -0.22200531]
 [-0.75467946  0.77982177  1.39835266 -0.8038702   1.444163  ]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [5]:
import numpy as np
A=np.random.randint(10, size=(4,5))
print("Matrix A:", A, sep='\n', end='\n\n')

B=np.dot(A.T, A)
print("Matrix B:", B, sep='\n', end='\n'*2)

C=np.dot(A, A.T)
print("Matrix С:", C, sep='\n', end='\n'*2)

print('матрицы равны' if (B.shape==C.shape and B==C) else 'матрицы не равны')

Matrix A:
[[8 3 3 9 8]
 [3 0 7 4 9]
 [5 1 2 6 4]
 [2 3 1 4 4]]

Matrix B:
[[102  35  57 122 119]
 [ 35  19  14  45  40]
 [ 57  14  63  71  99]
 [122  45  71 149 148]
 [119  40  99 148 177]]

Matrix С:
[[227 153 135  96]
 [153 155  89  65]
 [135  89  82  55]
 [ 96  65  55  46]]

матрицы не равны


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [4]:
import numpy as np
A=np.random.randint(10, size=(5,5))
B=np.random.randint(10, size=(5,5))
print(A)
np.diag(A)+np.diag(B)

[[7 4 3 4 0]
 [8 3 9 6 9]
 [2 5 0 5 4]
 [7 9 8 8 3]
 [9 9 9 1 2]]


array([ 8,  8,  6, 15,  4])

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [3]:
import numpy as np
A=np.random.randint(10, size=(3,3))
print(A)
print(f"Определитель A: {int(np.linalg.det(A))}", end='\n'*2)
print(f"Ранг матрицы A: {np.linalg.matrix_rank(A)}", end='\n'*2)
print(f"Спектр матрицы:\n {np.linalg.inv(A)}")

[[7 1 6]
 [5 8 6]
 [0 5 7]]
Определитель A: 297

Ранг матрицы A: 3

Спектр матрицы:
 [[ 0.08754209  0.07744108 -0.14141414]
 [-0.11784512  0.16498316 -0.04040404]
 [ 0.08417508 -0.11784512  0.17171717]]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [2]:
import numpy as np
def foo(x):
    return (x**2+3)/(x-2)

def create_array(a,b):
    return np.arange(a,b,0.01)

def main():
    try:
        a,b=map(int, input("Введите пределы интегрирования: ").split())
    except:
        print("Некорректно-введенные ")
    else:
        print(f"Примерное значение интеграла: {foo(create_array(a,b)).sum()}")

# a=create_array(1,2)
# foo(a).sum()
main()

Введите пределы интегрирования: 1 3
Примерное значение интеграла: 7881299347899160.0
